version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/advance"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/basic"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/minimial"
    schedule:
      interval: "monthly"
